# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'gateblu' do
    pod 'BLWebSocketsServer'
    pod 'Cordova', '~> 3.7'
end

target 'gatebluTests' do

end

