# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'gateblu' do
    pod 'PocketSocket'
    pod 'AFNetworking'
    pod 'SIOSocket'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON'
end

target 'gatebluTests' do

end

